apply.info=git repository
mysqldb.datasource.driver=com.mysql.jdbc.Driver
mysqldb.datasource.url=jdbc:mysql://localhost:3306/mybatis?characterEncoding =UTF-8"
mysqldb.datasource.username=root
mysqldb.datasource.password=489188
